const fs = require('fs');

const langs = ['en', 'sw', 'es', 'fr', 'de', 'zh', 'ar'];

const data = {
  en: {
    FunFact: { label: "THE WILD TRUTH", fact: "\"The Ngorongoro Crater is the world's largest unbroken volcanic caldera and home to over 25,000 large animals.\"" },
    About: { title: "Born in the <p>Wild.</p>", subtitle: "We don't just take you to Africa. We bring Africa into your soul.", legacy_badge: "The Heritage", legacy_title: "A legacy built on <br/><p>conservation.</p>", p1: "Asili Yetu simply translates to \"Our Nature\" in Swahili. But to us, it means far more. It is a promise to protect the sprawling, ancient ecosystems of Tanzania while sharing their absolute majesty with the world.", p2: "We realized early on that mass-tourism was diluting the magic of the Serengeti. The profound silence of the bush was being replaced by the roar of crowded minivans. We created Asili Yetu to restore the dignity of the expedition.", local_badge: "Local Tanzanian Ownership & Guides", pillars_title: "Our Three Pillars", pillars_sub: "We refuse to compromise on the quality of your experience. Every expedition is built upon three unbreakable promises.", p_lux: "Unapologetic Luxury", p_lux_sub: "From customized Land Cruisers with panoramic roofs to exclusive five-star tented camps. The bush is untamed, but your comfort is absolute.", p_safe: "Safety & Precision", p_safe_sub: "Navigating the African wild requires immense respect. Our guides are rigorously trained in safety protocols to ensure complete peace of mind.", p_cons: "Deep Conservation", p_cons_sub: "A portion of every booking funds anti-poaching units and local Maasai community schools. When you travel with us, you protect Tanzania." },
    Destinations: { badge: "The Lands of Legend", title: "Explore <p>Tanzania.</p>", sub: "From the endless golden plains of the Serengeti to the mist-shrouded crater of Ngorongoro, discover the world's most pristine wildlife sanctuaries.", time: "Best Time", wildlife: "Key Wildlife", scale: "Scale", view: "View Safaris Here" },
    Gallery: { badge: "The Lens", title: "Immersion <p>Gallery.</p>", sub: "A curated visual exhibition streaming live from our expeditions. No filters, just the raw majesty of our world.", awaiting: "Awaiting Signals", connect: "Connect your Instagram in the Admin Dashboard to stream live expedition photos here.", video: "Video", photo: "Photo", carousel: "Carousel" },
    Fleet: { title: "The Fleet", sub: "Travel in supreme comfort and safety with our customized 4x4 safari vehicles.", select: "SELECT A VEHICLE TO INSPECT", open: "Open Roof", seats: "Seats", ac: "Climate", fridge: "Fridge", specs: "Vehicle Specifications" }
  },
  sw: {
    FunFact: { label: "UKWELI WA PORINI", fact: "\"Bonge la Ngorongoro ndilo shimo kubwa zaidi la volkeno ambalo halijavunjika ulimwenguni na nyumbani kwa zaidi ya wanyama wakubwa 25,000.\"" },
    About: { title: "Tumezaliwa <p>Porini.</p>", subtitle: "Hatukupeleki tu Afrika. Tunaiweka Afrika ndani ya nafsi yako.", legacy_badge: "Urithi", legacy_title: "Urithi uliojengwa kwenye <br/><p>uhifadhi.</p>", p1: "Asili Yetu. Kwetu, inamaanisha zaidi. Ni ahadi ya kulinda mifumo ya ikolojia ya kale ya Tanzania na kushiriki utukufu wao na ulimwengu.", p2: "Tuligundua mapema kwamba utalii wa wingi uliyeyusha uchawi wa Serengeti. Tuliunda Asili Yetu kurejesha heshima ya safari.", local_badge: "Wamiliki na Waelekezi Wazawa", pillars_title: "Nguzo Zetu Tatu", pillars_sub: "Hatukubali kupunguza ubora wa uzoefu wako. Kila safari imejengwa kwenye ahadi tatu zisizovunjika.", p_lux: "Anasa Isiyojutia", p_lux_sub: "Kutoka Land Cruisers za kisasa hadi kambi za nyota tano. Pori ni kali, lakini faraja yako ni kamilifu.", p_safe: "Usalama na Umakini", p_safe_sub: "Kuzunguka pori la Afrika kunahitaji heshima kubwa. Waelekezi wetu wamepewa mafunzo makali.", p_cons: "Uhifadhi wa Kina", p_cons_sub: "Sehemu ya kila uhifadhi hufadhili vikosi dhidi ya ujangili na shule za Maasai. Unaposafiri nasi, unailinda Tanzania." },
    Destinations: { badge: "Ardhi za Hadithi", title: "Gundua <p>Tanzania.</p>", sub: "Kutoka tambarare za dhahabu za Serengeti hadi bonde lenye ukungu la Ngorongoro, gundua hifadhi za wanyamapori safi kabisa ulimwenguni.", time: "Wakati Bora", wildlife: "Wanyamapori Muhimu", scale: "Ukubwa", view: "Tazama Safari Hapa" },
    Gallery: { badge: "Lenzi", title: "Matunzio ya <p>Kuzama.</p>", sub: "Maonyesho ya kuona yanayotiririshwa moja kwa moja kutoka kwenye safari zetu. Ubora kamili wa asili.", awaiting: "Tunasubiri Ishara", connect: "Unganisha Instagram yako kwenye Dashibodi ili kutiririsha picha hapa.", video: "Video", photo: "Picha", carousel: "Albamu" },
    Fleet: { title: "Magari Yetu", sub: "Safiri kwa faraja na usalama mkubwa na magari yetu maalumu ya 4x4.", select: "CHAGUA GARI KUKAGUA", open: "Paa Wazi", seats: "Viti", ac: "Hali ya Hewa", fridge: "Friji", specs: "Maelezo ya Gari" }
  },
  es: {
    FunFact: { label: "LA VERDAD SALVAJE", fact: "\"El cráter del Ngorongoro es la caldera volcánica intacta más grande del mundo y alberga a más de 25,000 animales grandes.\"" },
    About: { title: "Nacidos en lo <p>Salvaje.</p>", subtitle: "No solo te llevamos a África. Llevamos a África a tu alma.", legacy_badge: "El Legado", legacy_title: "Un legado construido en la <br/><p>conservación.</p>", p1: "Asili Yetu se traduce como 'Nuestra Naturaleza'. Para nosotros, es una promesa de proteger los antiguos ecosistemas de Tanzania.", p2: "Nos dimos cuenta temprano de que el turismo masivo estaba diluyendo la magia del Serengeti. Creamos Asili Yetu para restaurar la dignidad de la expedición.", local_badge: "Propiedad y Guías Locales", pillars_title: "Nuestros Tres Pilares", pillars_sub: "Nos negamos a comprometer la calidad. Cada expedición se basa en tres promesas inquebrantables.", p_lux: "Lujo Intransigente", p_lux_sub: "Desde Land Cruisers personalizados hasta exclusivos campamentos de cinco estrellas. La selva es salvaje, pero tu confort es absoluto.", p_safe: "Seguridad y Precisión", p_safe_sub: "Navegar por la naturaleza africana exige un inmenso respeto. Nuestros guías están rigurosamente formados.", p_cons: "Conservación Profunda", p_cons_sub: "Una parte de cada reserva financia unidades contra la caza furtiva. Cuando viajas con nosotros, proteges Tanzania." },
    Destinations: { badge: "Tierras de Leyenda", title: "Explora <p>Tanzania.</p>", sub: "Desde las interminables llanuras doradas del Serengeti hasta el cráter envuelto en niebla del Ngorongoro.", time: "Mejor Época", wildlife: "Fauna Clave", scale: "Escala", view: "Ver Safaris Aquí" },
    Gallery: { badge: "La Lente", title: "Galería de <p>Inmersión.</p>", sub: "Una exhibición visual curada en vivo desde nuestras expediciones. Sin filtros, solo la cruda majestuosidad de nuestro mundo.", awaiting: "Esperando Señales", connect: "Conecta tu Instagram en el Dashboard para transmitir fotos en vivo aquí.", video: "Video", photo: "Foto", carousel: "Carrusel" },
    Fleet: { title: "La Flota", sub: "Viaja con suprema comodidad y seguridad con nuestros vehículos safari 4x4 personalizados.", select: "SELECCIONA UN VEHÍCULO PARA INSPECCIONAR", open: "Techo Abierto", seats: "Asientos", ac: "Clima", fridge: "Refrigerador", specs: "Especificaciones del Vehículo" }
  },
  fr: {
    FunFact: { label: "LA VÉRITÉ SAUVAGE", fact: "\"Le cratère du Ngorongoro est la plus grande caldeira volcanique intacte au monde et abrite plus de 25 000 grands animaux.\"" },
    About: { title: "Nés à <p>l'État Sauvage.</p>", subtitle: "Nous ne nous contentons pas de vous emmener en Afrique. Nous gravons l'Afrique dans votre âme.", legacy_badge: "L'Héritage", legacy_title: "Un héritage fondé sur la <br/><p>conservation.</p>", p1: "Asili Yetu se traduit par 'Notre Nature'. Pour nous, c'est la promesse de protéger les anciens écosystèmes tanzaniens.", p2: "Le tourisme de masse diluait la magie du Serengeti. Nous avons créé Asili Yetu pour restaurer la dignité de l'expédition.", local_badge: "Propriétaires et Guides Locaux", pillars_title: "Nos Trois Piliers", pillars_sub: "Chaque expédition repose sur trois promesses inviolables.", p_lux: "Luxe Inconditionnel", p_lux_sub: "Des Land Cruisers sur mesure aux camps de luxe cinq étoiles. La brousse est indomptée, mais votre confort est absolu.", p_safe: "Sécurité et Précision", p_safe_sub: "Naviguer dans la nature africaine nécessite un immense respect.", p_cons: "Conservation Profonde", p_cons_sub: "Une partie de chaque réservation finance les unités anti-braconnage. En voyageant avec nous, vous protégez la Tanzanie." },
    Destinations: { badge: "Terres de Légende", title: "Explorez la <p>Tanzanie.</p>", sub: "Des plaines dorées du Serengeti au cratère brumeux du Ngorongoro.", time: "Meilleure Période", wildlife: "Faune Clé", scale: "Échelle", view: "Voir les Safaris Ici" },
    Gallery: { badge: "L'Objectif", title: "Galerie <p>d'Immersion.</p>", sub: "Une exposition visuelle en direct de nos expéditions. Sans filtre, juste la majesté.", awaiting: "En attente de signaux", connect: "Connectez votre Instagram dans le tableau de bord pour diffuser des photos ici.", video: "Vidéo", photo: "Photo", carousel: "Carrousel" },
    Fleet: { title: "La Flotte", sub: "Voyagez dans un confort suprême avec nos véhicules safari 4x4.", select: "SÉLECTIONNER UN VÉHICULE", open: "Toit Ouvert", seats: "Sièges", ac: "Climat", fridge: "Réfrigérateur", specs: "Spécifications du Véhicule" }
  },
  de: {
    FunFact: { label: "DIE WILDE WAHRHEIT", fact: "\"Der Ngorongoro-Krater ist die größte ungebrochene vulkanische Caldera der Welt und beherbergt über 25.000 große Tiere.\"" },
    About: { title: "Geboren in der <p>Wildnis.</p>", subtitle: "Wir bringen nicht nur Sie nach Afrika. Wir bringen Afrika in Ihre Seele.", legacy_badge: "Das Erbe", legacy_title: "Ein Erbe erbaut auf <br/><p>Naturschutz.</p>", p1: "Asili Yetu bedeutet 'Unsere Natur'. Für uns ist es das Versprechen, Tansanias Ökosysteme zu schützen.", p2: "Der Massentourismus verwässerte die Magie der Serengeti. Wir haben Asili Yetu gegründet, um die Würde der Expedition wiederherzustellen.", local_badge: "Lokales Eigentum & Guides", pillars_title: "Unsere Drei Säulen", pillars_sub: "Wir gehen bei der Qualität keine Kompromisse ein. Jede Expedition basiert auf drei Versprechen.", p_lux: "Kompomissloser Luxus", p_lux_sub: "Maßgeschneiderte Land Cruiser und Fünf-Sterne-Zeltcamps. Der Busch ist ungezähmt, Ihr Komfort absolut.", p_safe: "Sicherheit & Präzision", p_safe_sub: "Unsere Guides sind streng im Sicherheitsprotokoll geschult.", p_cons: "Tiefgreifender Naturschutz", p_cons_sub: "Ein Teil jeder Buchung finanziert Anti-Wilderer-Einheiten. Wenn Sie mit uns reisen, schützen Sie Tansania." },
    Destinations: { badge: "Länder der Legenden", title: "Erkunden Sie <p>Tansania.</p>", sub: "Von den endlosen goldenen Ebenen der Serengeti bis zum wolkenverhangenen Krater des Ngorongoro.", time: "Beste Zeit", wildlife: "Wichtigste Tierwelt", scale: "Größe", view: "Safaris Hier Ansehen" },
    Gallery: { badge: "Die Linse", title: "Immersions- <p>Galerie.</p>", sub: "Eine kuratierte visuelle Ausstellung live von unseren Expeditionen.", awaiting: "Warten auf Signale", connect: "Verbinden Sie Ihr Instagram im Admin-Dashboard.", video: "Video", photo: "Foto", carousel: "Karussell" },
    Fleet: { title: "Die Flotte", sub: "Reisen Sie mit höchstem Komfort und Sicherheit in unseren maßgeschneiderten Geländewagen.", select: "FAHRZEUG ZUR INSPEKTION AUSWÄHLEN", open: "Offenes Dach", seats: "Sitze", ac: "Klima", fridge: "Kühlschrank", specs: "Fahrzeugspezifikationen" }
  },
  zh: {
    FunFact: { label: "荒野真相", fact: "\"恩戈罗恩戈罗火山口是世界上最大的未破裂火山破火山口，拥有超过25,000只大型动物。\"" },
    About: { title: "生于<p>荒野。</p>", subtitle: "我们不仅仅带您去非洲。我们把非洲带入您的灵魂。", legacy_badge: "传承", legacy_title: "建立在<br/><p>保护</p>之上的传承。", p1: "Asili Yetu意为“我们的自然”。对我们来说，这是保护坦桑尼亚古老生态系统的承诺。", p2: "大众旅游正在冲淡塞伦盖蒂的魔力。我们创立了Asili Yetu以恢复探险的尊严。", local_badge: "坦桑尼亚本地所有权及向导", pillars_title: "我们的三大支柱", pillars_sub: "我们在体验质量上毫不妥协。每一次远征都建立在三个不可打破的承诺之上。", p_lux: "不妥协的奢华", p_lux_sub: "从定制的陆地巡洋舰到专属的五星级帐篷营地。丛林未被驯服，但您的舒适是绝对的。", p_safe: "安全与精准", p_safe_sub: "我们的向导在安全协议方面受过严格训练。", p_cons: "深度保护", p_cons_sub: "每个预订的一部分将资助反偷猎单位。与我们同行即在保护坦桑尼亚。" },
    Destinations: { badge: "传奇之地", title: "探索<p>坦桑尼亚。</p>", sub: "从塞伦盖蒂无尽的金色平原到恩戈罗恩戈罗的雾笼火山口。", time: "最佳时间", wildlife: "主要野生动物", scale: "规模", view: "点击此处查看狩猎行程" },
    Gallery: { badge: "镜头", title: "沉浸式<p>图库。</p>", sub: "从我们的探险中实时流传的精选视觉展览。", awaiting: "等待信号", connect: "在仪表板中连接您的Instagram以在此处传输实时图片。", video: "视频", photo: "图片", carousel: "轮播" },
    Fleet: { title: "车队", sub: "我们定制的4x4狩猎越野车让您在极大的舒适和安全中旅行。", select: "选择一辆越野车进行查看", open: "开放式车顶", seats: "座位", ac: "空调", fridge: "冰箱", specs: "车辆规格" }
  },
  ar: {
    FunFact: { label: "الحقيقة البرية", fact: "\"فوهة نجورونجورو هي أكبر كالديرا بركانية متصلة في العالم وتعد موطناً لأكثر من 25,000 حيوان ضخم.\"" },
    About: { title: "ولدنا في <p>البرية.</p>", subtitle: "نحن لا نأخذك إلى أفريقيا فحسب. نحن ندخل أفريقيا إلى روحك.", legacy_badge: "الإرث", legacy_title: "إرث مبني على <br/><p>الحفظ.</p>", p1: "أسيلي ييتو تعني 'طبيعتنا'. هو وعد بحماية النظم البيئية في تنزانيا.", p2: "أدركنا أن السياحة الجماعية تضعف سحر سيرينجيتي. أنشأنا أسيلي ييتو لاستعادة كرامة الحملات.", local_badge: "ملكية وأدلاء محليين", pillars_title: "أعمدتنا الثلاثة", pillars_sub: "كل رحلة استكشافية مبنية على ثلاثة وعود لا تنكسر.", p_lux: "فخامة لا تضاهى", p_lux_sub: "من سيارات لاندكروزر المخصصة إلى خيام الخمس نجوم. البرية قاسية ولكن راحتك مطلقة.", p_safe: "الأمان والدقة", p_safe_sub: "مرشدونا مدربون بصرامة لضمان راحة بالك التامة.", p_cons: "المحافظة العميقة", p_cons_sub: "جزء من كل حجز يمول وحدات مكافحة الصيد الجائر." },
    Destinations: { badge: "أراضي الأساطير", title: "اكتشف <p>تنزانيا.</p>", sub: "من السهول الذهبية لسيرينجيتي إلى فوهة نجورونجورو المغطاة بالضباب.", time: "أفضل وقت", wildlife: "الحياة البرية الرئيسية", scale: "المساحة", view: "شاهد الرحلات هنا" },
    Gallery: { badge: "العدسة", title: "معرض <p>الاندماج.</p>", sub: "معرض مرئي مباشر من حملاتنا. بدون فلاتر.", awaiting: "في انتظار إشارات", connect: "قم بتوصيل حساب إنستغرام الخاص بك هنا.", video: "فيديو", photo: "صورة", carousel: "شريط صور" },
    Fleet: { title: "الأسطول", sub: "سافر براحة تامة وأمان مع سيارات الدفع الرباعي المجهزة.", select: "اختر سيارة للفحص", open: "سقف مفتوح", seats: "مقاعد", ac: "مكيف", fridge: "ثلاجة", specs: "مواصفات المركبة" }
  }
}

for (const lang of langs) {
  const path = `./messages/${lang}.json`;
  const file = JSON.parse(fs.readFileSync(path, 'utf8'));
  file["FunFact"] = data[lang].FunFact;
  file["About"] = data[lang].About;
  file["Destinations"] = data[lang].Destinations;
  file["Gallery"] = data[lang].Gallery;
  file["Fleet"] = data[lang].Fleet;
  fs.writeFileSync(path, JSON.stringify(file, null, 2));
}

console.log("ALL DICTIONARIES UPDATED WITH FULL TRANSLATIONS");
