const fs = require('fs');

const langs = ['en', 'sw', 'es', 'fr', 'de', 'zh', 'ar'];

const dicts = {
  en: { booking: "Booking", luxury_camps: "Luxury Tented Camps", private_guide: "Private Guide Included", step: "Step", of: "of", traveler_info: "Traveler Information", who_joining: "Who will be joining us on this adventure?", full_name: "Full Name", email_address: "Email Address", continue: "Continue", back: "Back", enhance: "Enhance Your Safari", hot_air_balloon: "Hot Air Balloon Flight", pro_photo: "Pro Photography Kit", dietary: "Dietary Requirements", dietary_placeholder: "Vegan, nut allergy, etc.", final_review: "Final Review", confirm_voyage: "Confirm Voyage", lead_explorer: "Lead Explorer", contact: "Contact", addons: "Addons", finalizing: "Finalizing...", initialize: "Initialize Expedition", welcome: "Welcome to the Wild.", confirmed: "Your majestic expedition is confirmed.", return: "Return to Base" },
  sw: { booking: "Uhifadhi", luxury_camps: "Kambi za Kifahari", private_guide: "Mwongoza Safari Binafsi", step: "Hatua", of: "ya", traveler_info: "Taarifa za Msafiri", who_joining: "Nani atajiunga nasi kwenye hii safari?", full_name: "Jina Kamili", email_address: "Barua Pepe", continue: "Endelea", back: "Rudi", enhance: "Boresha Safari Yako", hot_air_balloon: "Safari ya Puto", pro_photo: "Vifaa vya Picha", dietary: "Mahitaji ya Lishe", dietary_placeholder: "Vegan, mzio wa karanga, n.k.", final_review: "Mapitio ya Mwisho", confirm_voyage: "Thibitisha Safari", lead_explorer: "Mkuu Mpelelezi", contact: "Mawasiliano", addons: "Nyongeza", finalizing: "Inakamilisha...", initialize: "Anzisha Safari", welcome: "Karibu Porini.", confirmed: "Safari yako imethibitishwa kikamilifu.", return: "Rudi Mwanzo" },
  es: { booking: "Reserva", luxury_camps: "Campamentos de Lujo", private_guide: "Guía Privado Incluido", step: "Paso", of: "de", traveler_info: "Información del Viajero", who_joining: "¿Quién nos acompañará en esta aventura?", full_name: "Nombre Completo", email_address: "Correo Electrónico", continue: "Continuar", back: "Volver", enhance: "Mejora tu Safari", hot_air_balloon: "Vuelo en Globo", pro_photo: "Kit de Fotografía", dietary: "Requisitos Dietéticos", dietary_placeholder: "Vegano, alergia a las nueces, etc.", final_review: "Revisión Final", confirm_voyage: "Confirmar Viaje", lead_explorer: "Explorador Principal", contact: "Contacto", addons: "Complementos", finalizing: "Finalizando...", initialize: "Iniciar Expedición", welcome: "Bienvenido a lo Salvaje.", confirmed: "Tu majestuosa expedición está confirmada.", return: "Volver a la Base" },
  fr: { booking: "Réservation", luxury_camps: "Camps de Tentes de Luxe", private_guide: "Guide Privé Inclus", step: "Étape", of: "sur", traveler_info: "Informations sur le Voyageur", who_joining: "Qui se joindra à cette aventure ?", full_name: "Nom Complet", email_address: "Adresse E-mail", continue: "Continuer", back: "Retour", enhance: "Améliorez votre Safari", hot_air_balloon: "Vol en Montgolfière", pro_photo: "Kit Photographie Pro", dietary: "Besoins Diététiques", dietary_placeholder: "Végétalien, allergie aux noix, etc.", final_review: "Revue Finale", confirm_voyage: "Confirmer le Voyage", lead_explorer: "Explorateur Principal", contact: "Contact", addons: "Options", finalizing: "Finalisation...", initialize: "Initier l'Expédition", welcome: "Bienvenue dans la Nature Morte.", confirmed: "Votre expédition majestueuse est confirmée.", return: "Retour à la Base" },
  de: { booking: "Buchung", luxury_camps: "Luxuszeltlager", private_guide: "Privatführer Inbegriffen", step: "Schritt", of: "von", traveler_info: "Reiseinformationen", who_joining: "Wer wird uns auf diesem Abenteuer begleiten?", full_name: "Vollständiger Name", email_address: "E-Mail", continue: "Weiter", back: "Zurück", enhance: "Verbessern Sie Ihre Safari", hot_air_balloon: "Heißluftballonfahrt", pro_photo: "Profi-Foto-Set", dietary: "Ernährungsbedürfnisse", dietary_placeholder: "Vegan, Nussallergie, etc.", final_review: "Letzte Überprüfung", confirm_voyage: "Reise Bestätigen", lead_explorer: "Hauptentdecker", contact: "Kontakt", addons: "Zusätze", finalizing: "Abschließen...", initialize: "Expedition Starten", welcome: "Willkommen in der Wildnis.", confirmed: "Ihre majestätische Expedition ist bestätigt.", return: "Zurück zur Basis" },
  zh: { booking: "预订", luxury_camps: "豪华帐篷营地", private_guide: "包含私人向导", step: "步骤", of: "共", traveler_info: "旅客信息", who_joining: "谁将加入我们的冒险？", full_name: "全名", email_address: "电子邮件", continue: "继续", back: "返回", enhance: "增强您的Safari", hot_air_balloon: "热气球飞行", pro_photo: "专业摄影套件", dietary: "饮食要求", dietary_placeholder: "素食，坚果过敏等", final_review: "最终审核", confirm_voyage: "确认航程", lead_explorer: "首席探险家", contact: "联系方式", addons: "附加选项", finalizing: "完成中...", initialize: "启动探险", welcome: "欢迎来到荒野", confirmed: "您宏伟的远征已确认", return: "返回基地" },
  ar: { booking: "الحجز", luxury_camps: "مخيمات فاخرة", private_guide: "مرشد خاص مشمول", step: "خطوة", of: "من", traveler_info: "معلومات المسافر", who_joining: "من سينضم إلينا في هذه المغامرة؟", full_name: "الاسم الكامل", email_address: "البريد الإلكتروني", continue: "متابعة", back: "رجوع", enhance: "عزز رحلة السفاري", hot_air_balloon: "طيران بالمنطاد", pro_photo: "مجموعة التصوير", dietary: "المتطلبات الغذائية", dietary_placeholder: "نباتي، حساسية المكسرات، إلخ.", final_review: "المراجعة النهائية", confirm_voyage: "تأكيد الرحلة", lead_explorer: "كبير المستكشفين", contact: "جهة الاتصال", addons: "إضافات", finalizing: "جارٍ الانتهاء...", initialize: "بدء الحملة", welcome: "مرحباً بكم في البرية.", confirmed: "تم تأكيد رحلتكم المهيبة.", return: "العودة إلى القاعدة" }
}

for (const lang of langs) {
  const path = `./messages/${lang}.json`;
  const file = JSON.parse(fs.readFileSync(path, 'utf8'));
  file["Booking"] = dicts[lang];
  fs.writeFileSync(path, JSON.stringify(file, null, 2));
}

console.log("SUCCESS");
